config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root :to => 'homes#top'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
      get :dm
    end
    get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw'
  end

  resources :notifications, only: [:index]

  resources :want_items, only: [:index, :create, :update, :destroy] do
    resources :want_answers, only: [:create, :destroy]
    member do
      patch 'answer_close' => 'want_items#answer_close', as: 'answer_close'
    end
  end

  resources :recommends, only: [:index, :new, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :categories, only: [:show, :create, :destroy] do
    member do
      get 'want_item' => 'categories#want_item'
      get 'recommend' => 'categories#recommend'
    end
  end

  resources :category_groups, only: [:show, :create, :destroy] do
    member do
      get 'want_item' => 'category_groups#want_item'
      get 'recommend' => 'category_groups#recommend'
    end
  end

  resources :rooms, only: [:index]
  resources :letters, only: [:create]

  get '/search', to: 'searches#search'
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :recommend, optional: true
  belongs_to :want_answer, optional: true
  belongs_to :room, optional: true
  belongs_to :letter, optional: true

  belongs_to :visitor, class_name: "User", foreign_key: "visitor_id"
  belongs_to :visited, class_name: "User", foreign_key: "visited_id"
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @notifications = @user.passive_notifications.page(params[:page]).per(15)
    @notifications.where(is_checked: false).each do |notification|
      notification.update(is_checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class="row p-4">
  <div class="col-2 offset-1 text-center">
    <%= link_to user_path(visitor) do %>
      <%= image_tag visitor.get_profile_image(80,80), class: "rounded-circle mr-3" %>
      <strong>
        <%= visitor.name %>
      </strong>
    <% end %>
  </div>
    <% case notification.action %>
      <% when 'follow' then %>
        <div class="col-8 d-flex align-items-center">
          <p class="mr-2">さんにフォローされました</p>
          <% unless current_user.following?(visitor) %>
            <span class="follow-btn-<%= visitor.id %>"><%= render 'relationships/btn', user: visitor %></span>
          <% end %>
        </div>
      <% when 'fav' then %>
        <div class="col-8 d-flex align-items-center">
          <p>さんが<i class="fas fa-heart heart"></i>しました</p>
        </div>
        <div class="mx-auto pb-3 recommend-item">
          <div class="item">
            <%= image_tag notification.recommend.get_recommend_image(260,260) %>
            <p><%= safe_join(notification.recommend.content.split("\n"),tag(:br)) %></p>
            <% if notification.recommend.url.present? %>
              <p><%= raw Rinku.auto_link(notification.recommend.url, :all, 'target="_blank"').html_safe %></p>
            <% end %>
          </div>
          <div class="mt-3 recommend-user">
            <%= link_to user_path(notification.recommend.user) do%>
              <%= image_tag notification.recommend.user.get_profile_image(50,50), class: "rounded-circle mr-4" %>
              <%= notification.recommend.user.name %>
            <% end %>
          </div>
        </div>
      <% when 'answer' then %>
        <div class="col-8 d-flex align-items-center">
          <p>さんが投稿にコメントしました</p>
        </div>
        <div class="col-12 my-3 want-item">
          <div class="col-md-10 offset-1 px-5 want-content">
            <div class="row genre-box">
              <% if notification.want_answer.want_item.category.present? %>
                <%= notification.want_answer.want_item.category.name %>
              <% end %>
            </div>
            <div class="row mt-4 mb-3">
              <%= notification.want_answer.want_item.content %>
            </div>
            <% if notification.want_answer.want_item.want_image.present? %>
              <div class="row pb-3">
                <%= image_tag notification.want_answer.want_item.get_want_image(400,300) %>
              </div>
            <% end %>
            <% if notification.want_answer.want_item.budget.present? %>
              <div class="row pb-2">
                予算：<%= notification.want_answer.want_item.budget %>円
              </div>
            <% end %>
            <div class="row pb-2">
              <% notification.want_answer.want_item.tags.each do |tag| %>
                &ensp;
                <span class="want-tags">
                  <%= link_to search_path(content: tag.name, model: "tag", method: "perfect") do %>
                    <%= tag.name %>
                  <% end %>
                </span>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-10 offset-1 mt-4">
          <%= render 'want_answers/index', want_item: notification.want_answer.want_item %>
        </div>
      <% when 'dm' %>
        <div class="col-8 d-flex align-items-center">
          <p>さんからレターが届きました</p>
        </div>
        <div class="col-8 offset-3">
          <%= link_to dm_user_path(visitor) do %>
            <%= truncate(notification.letter.message, length: 20, omission: '... (一部表示)') %>
          <% end %>
        </div>
    <% end %>
</div>
<div class="small text-muted text-right">
  <%= time_ago_in_words(notification.created_at).upcase %>
</div>
<hr>

app/views/notifications/index.html.erb
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
    </div>
    <div class="col-md-1 mypage-menu">
      <%= render 'users/mypage_menu', user: @user %>
    </div>
    <div class="col-md-8">
      <% if notifications.exists? %>
        <%= render notifications %>
        <%= paginate notifications %>
      <% else %>
        <p class="ml-4">
          通知はありません
        </p>
      <% end %>
    </div>
  </div>
</div>