config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root :to => 'homes#top'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
      get :dm
    end
    get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw'
  end

  resources :notifications, only: [:index]

  resources :want_items, only: [:index, :create, :update, :destroy] do
    resources :want_answers, only: [:create, :destroy]
    member do
      patch 'answer_close' => 'want_items#answer_close', as: 'answer_close'
    end
  end

  resources :recommends, only: [:index, :new, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :categories, only: [:show, :create, :destroy] do
    member do
      get 'want_item' => 'categories#want_item'
      get 'recommend' => 'categories#recommend'
    end
  end

  resources :category_groups, only: [:show, :create, :destroy] do
    member do
      get 'want_item' => 'category_groups#want_item'
      get 'recommend' => 'category_groups#recommend'
    end
  end

  resources :rooms, only: [:index]
  resources :letters, only: [:create]

  get '/search', to: 'searches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :want_items, dependent: :destroy
  has_many :want_answers, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :letters, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 10 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no-image.png")
      profile_image.attach(io: File.open(file_path), filename: "no-image.png", content_type: "image")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def self.search_for(content)
    User.where('name LIKE ?', '%' + content + '%')
  end

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :favorites]

  def index
    if current_user.is_admin == true
      @users = User.where.not(is_admin: true).page(params[:page]).per(10)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      @want_items = WantItem.where(user_id: current_user.followings.ids, is_answer: true).page(params[:page]).per(10)
      @recommends = Recommend.where(user_id: current_user.followings.ids).page(params[:page]).per(10)
      params[:user_id]
      params[:id]
    else
      @want_items = @user.want_items.page(params[:page]).per(10)
      @recommends = @user.recommends.page(params[:page]).per(10)
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:alert] = "必須項目が入力されていません"
      render 'edit'
    end
  end

  def favorites
    favorites = Favorite.where(user_id: @user.id).pluck(:recommend_id)
    @favorite_recommends = Recommend.find(favorites)
  end

  def unsubscribe
    @user = User.find(params[:user_id])
  end

  def withdraw
    @user = User.find(params[:user_id])
    if @user.is_active == true
      @user.update(is_active: false)
    else
      @user.update(is_active: true)
    end
    if current_user.is_admin == false
      reset_session
      redirect_to root_path
    else
      redirect_to users_path
    end
  end

  def dm
    @user = User.find(params[:id])
    # 自分と相手のIDをもつEntryがない場合は作る、あれば取得する
    my_room_ids = current_user.entries.pluck(:room_id)
    room_ids = @user.entries.pluck(:room_id)
    room_id = my_room_ids & room_ids

    if room_id.present?
      @room = Room.find(room_id.first)
    else
      @room = Room.new
      @room.save!
      current_user.entries.create!(room_id: @room.id)
      @user.entries.create!(room_id: @room.id)
    end

    @letters = @room.letters
    @letter = Letter.new(room_id: @room.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :instagram, :twitter, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<% users.each do |user| %>
  <div class="row">
    <div class="col-md-4 text-center my-2">
      <%= link_to user_path(user) do %>
        <%= image_tag user.get_profile_image(100,100), class: "rounded-circle" %>
      <% end %>
    </div>
    <div class="col-md-3 d-flex align-items-center">
      <%= link_to user_path(user) do %>
        <%= user.name %>
      <% end %>
    </div>
    <% if current_user.is_admin == false %>
      <div class="col-md-2 offset-1 d-flex align-items-center follow-btn-<%= user.id %>">
        <%= render "relationships/btn", user: user %>
      </div>
      <div class="col-md-2 d-flex align-items-center letter-btn-<%= user.id %>">
        <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
          <i class="fas fa-handshake mx-3"></i>
          <%= render "letters/letter_btn", user: user %>
        <% end %>
      </div>
    <% else %>
      <% if user.is_active == true %>
        <div class="col-md-4 offset-1 d-flex align-items-center">
          <%= link_to "ユーザーの利用を停止する", user_withdraw_path(user), method: :patch, "data-confirm" => "ユーザーの利用を停止しますか？" %>
        </div>
      <% else %>
        <div class="col-md-4 offset-1 d-flex align-items-center">
          <%= link_to "ユーザーの利用を再開する", user_withdraw_path(user), method: :patch %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>
<%= paginate users %>

app/views/users/_info.html.erb
<div class="polaroid my-3">
  <% if current_user == user && current_user.is_admin == false %>
    <%= link_to edit_user_path(user) do %>
      <i class="fas fa-cog gear"></i>
    <% end %>
  <% end %>

  <%= image_tag user.get_profile_image(180,180) %>
  <p class="user-content">
    <%= user.name %>
    <% if user.instagram.present? %>
      <%= link_to user.instagram, target: "_blank", rel: "noopener noreferrer" do %>
        <%=image_tag "instagram.png", class: "icon" %>
      <% end %>
    <% end %>
    <% if user.twitter.present? %>
      <%= link_to user.twitter, target: "_blank", rel: "noopener noreferrer" do %>
        <%=image_tag "twitter.png", class: "icon" %>
      <% end %>
    <% end %>
  </p>
  <p class="introduction"><%= user.introduction %></p>
</div>
<div class="mb-3">
</div>

<div class="row mb-3 follow-btn-<%= user.id %>">
  <%= render "relationships/btn", user: user %>
</div>
<div class="row mb-3 letter-btn-<%= user.id %>">
  <%= render "letters/letter_btn", user: user %>
</div>

app/views/users/_mypage_menu.html.erb
<div class="mypage-menu">
  <ul>
    <li class="text-center flash">
      <%= link_to user_path(user) do %>
        <i class="fas fa-home"></i>
      <% end %>
    </li>
    <hr>
    <li class="text-center flash">
      <%= link_to favorites_user_path(user) do %>
        <i class="fas fa-heart"></i>
      <% end %>
    </li>
    <hr>
    <li class="text-center flash">
      <%= link_to user_followings_path(user) do %>
        <i class="fas fa-praying-hands"></i>
      <% end %>
    </li>
    <hr>
    <li class="text-center flash">
      <%= link_to notifications_path do %>
        <% if current_user.passive_notifications.where(is_checked: false).exists? %>
          <i class="fas fa-bell swing"></i>
        <% else %>
          <i class="fas fa-bell"></i>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>

app/views/users/dm.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "rooms/index", rooms: current_user.rooms %>
    </div>
    <div class="col-md-7 offset-1 room">
      <h5 class="room-header" data-room="<%= @room.id %>" data-user="<%= current_user.id %>"><%= link_to @user.name, user_path(@user) %></h5>
      <div class="message-window">
        <% @letters.each do |letter| %>
          <div class="message-list my-3">
            <% if letter.user_id == current_user.id %>
              <p style="text-align: right;"><%= letter.message %></p>
            <% else %>
              <p style="text-align: left;"><%= image_tag @user.get_profile_image(35,35), class: "rounded-circle mr-3" %><%= letter.message %></p>
            <% end %>
          </div>
        <% end %>

      </div>
      <div class="errors">
          <%= render "layouts/errors", obj: @letter %>
        </div>
        <div class=" chat-input">
          <%= form_with model: @letter, data: {remote: true} do |f| %>
            <%= f.text_field :message, class: "w-100 form-control message-input", placeholder: "your message here" %>
            <%= f.hidden_field :room_id %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4">
      <%= render "info", user: @user %>
    </div>

    <div class="col-md-7 offset-1">
      <h4 class="m-4">edit profile</h4>
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group edit-profile">
          <%= f.file_field :profile_image, class: "form-control-file", accept: "image/*" %>
        </div>
        <div class="form-group edit-profile">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group edit-profile">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group edit-profile">
          <%= f.label :instagram %>
          <%= f.text_field :instagram, class: "form-control", placeholder: "Instagram URL" %>
        </div>
        <div class="form-group edit-profile">
          <%= f.label :twitter %>
          <%= f.text_field :twitter, class: "form-control", placeholder: "Twitter URL" %>
        </div>
        <div class="form-group edit-profile mt-5">
          <%= f.submit "send", class: "btn btn-outline-secondary btn-block" %>
        </div>
        <div class="form-group edit-profile">
          <%= link_to "退会する", user_unsubscribe_path(@user), class: "btn btn-sm btn-default btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "info", user: @user %>
    </div>
    <div class="col-md-1 mypage-menu d-flex flex-column">
      <%= render 'mypage_menu', user: @user %>
    </div>
    <div class="col-md-8">
      <h4>ラブ</h4>
      <div class="d-flex flex-wrap">
        <%= render 'recommends/index', recommends: @favorite_recommends %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto pt-4">
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 side-menu">
      <%= render "info", user: @user %>
    </div>
    <div class="col-md-1 side-menu">
      <% if @user == current_user %>
        <%= render 'mypage_menu', user: @user %>
      <% end %>
    </div>
    <div class="col-md-8">
      <h4 class="ja">ウォント</h4>
      <%= render 'want_items/index', want_items: @want_items %>

      <h4 class="ja">リコメンド</h4>
      <div class="row d-flex">
        <%= render 'recommends/index', recommends: @recommends %>
      </div>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4 side-menu">
      <%= render "info", user: @user %>
    </div>
    <div class="col-md-7 offset-1 pt-5">
      <h5 class="confirm text-center mb-5">本当に退会しますか？</h2>
      <p class="confirm-text text-center mb-5">投稿、他ユーザとのメッセージ、お気に入り機能等が利用できなくなります。<br>退会する場合は、「退会する」をクリックしてください。</h3>
      <div class="text-center mt-4">
        <%= link_to "back", root_path, class: "btn btn-outline-secondary mx-5" %>
        <%= link_to "退会する", user_withdraw_path, method: :patch, "data-confirm" => "退会すると元には戻せません。本当によろしいですか？", class: "btn btn-default btn-sm mx-5" %>
      </div>
    </div>
  </div>
</div>