config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root :to => 'homes#top'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
      get :dm
    end
    get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw'
  end

  resources :notifications, only: [:index]

  resources :want_items, only: [:index, :create, :update, :destroy] do
    resources :want_answers, only: [:create, :destroy]
    member do
      patch 'answer_close' => 'want_items#answer_close', as: 'answer_close'
    end
  end

  resources :recommends, only: [:index, :new, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :categories, only: [:show, :create, :destroy] do
    member do
      get 'want_item' => 'categories#want_item'
      get 'recommend' => 'categories#recommend'
    end
  end

  resources :category_groups, only: [:show, :create, :destroy] do
    member do
      get 'want_item' => 'category_groups#want_item'
      get 'recommend' => 'category_groups#recommend'
    end
  end

  resources :rooms, only: [:index]
  resources :letters, only: [:create]

  get '/search', to: 'searches#search'
end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_one_attached :recommend_image

  validates :content, presence: true, length: { maximum: 140 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_fav!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and recommend_id = ? and action = ? ", current_user.id, user_id, id, 'fav'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        recommend_id: id,
        visited_id: user_id,
        action: 'fav'
      )
      notification.save if notification.valid?
    end
  end

  def get_recommend_image(width, height)
    unless recommend_image.attached?
      file_path = Rails.root.join("app/assets/images/no-image.png")
      recommend_image.attach(io: File.open(file_path), filename: "no-image.png", content_type: "image")
    end
    recommend_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content)
    Recommend.where('content LIKE ?', '%' + content + '%')
  end
end

app/controllers/recommends_controller.rb
class RecommendsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @recommends = Recommend.page(params[:page]).per(7).order(created_at: :desc)
    if params[:id].present?
      @recommend = Recommend.find(params[:id])
    else
      @recommend = Recommend.new
    end
  end

  def create
    @recommend = Recommend.new(recommend_params)
    @recommend.user_id = current_user.id
    if @recommend.save
      flash[:notice] = "「オススメ！」を投稿しました"
      redirect_to recommends_path
    else
      flash[:alert] = "必須項目が入力されていません"
      @recommends = Recommend.page(params[:page]).per(7).order(created_at: :desc)
      @user = current_user
      render 'index'
    end
  end

  def update
    if @recommend.update(recommend_params)
      flash[:notice] = "投稿を編集しました"
      redirect_to recommends_path
    else
      flash[:alert] = "必須項目が入力されていません"
      @recommends = Recommend.page(params[:page]).per(7).order(created_at: :desc)
      @user = current_user
      render 'index'
    end
  end

  def destroy
    @recommend.destroy!
    flash[:notice] = "投稿を削除しました"
    redirect_to recommends_path
  end

  private
  def ensure_correct_user
    @recommend = Recommend.find(params[:id])
    unless @recommend.user == current_user || current_user.is_admin == true
      redirect_to recommends_path
    end
  end

  def recommend_params
    params.require(:recommend).permit(:category_id, :content, :recommend_image, :url)
  end
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/views/recommends/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4><div class="modal-title">リコメンド</div></h4>
    </div>
    <div class="modal-body">
      <%= form_with model: recommend do |f| %>
        <div class="row pt-5">
          <div class="col-md-12 form-group mb-3 reccomend-form">
            <%= f.file_field :recommend_image, class: "form-control-file", accept: "image/*" %>
          </div>
          <div class="col-md-12 form-group reccomend-form">
            <%= f.text_area :content, class: "form-control", placeholder: "こんな服買った！" %>
          </div>
          <div class="col-md-11 form-group reccomend-form">
            <%= f.text_field :url, class: "form-control", placeholder: "ショップURL" %>
          </div>
          <div class="col-md-5 form-group reccomend-form">
            <%= f.grouped_collection_select(:category_id, CategoryGroup.all, :categories, :name, :id, :name, {prompt: "-- カテゴリ --"}, {class: "form-control input-sm"}) %>
          </div>
          <div class="col-11 form-group text-center">

            <% if params[:id].present? %>
              <%= f.submit "recommend edit", class: 'btn btn-outline-secondary btn-sm px-3' %>
            <% else %>
              <%= f.submit "recommend", class: 'btn btn-outline-secondary btn-sm px-3' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">exit</button>
      </div>
  </div>
</div>

app/views/recommends/_index.html.erb
<% recommends.each do |recommend| %>
  <div class="m-3 pb-3 recommend-item">
    <div class="row genre-box">
      <%= link_to recommend.category.category_group.name, recommend_category_group_path(recommend.category.category_group) %> /
      <%= link_to recommend.category.name, recommend_category_path(recommend.category) %>
    </div>
    <div class="item">
      <%= image_tag recommend.get_recommend_image(260,260) %>
      <p><%= safe_join(recommend.content.split("\n"),tag(:br)) %></p>
      <% if recommend.url.present? %>
        <p><%= raw Rinku.auto_link(recommend.url, :all, 'target="_blank"').html_safe %></p>
      <% end %>
    </div>
    <div class="mt-3 recommend-user">
      <%= link_to user_path(recommend.user) do%>
        <%= image_tag recommend.user.get_profile_image(50,50), class: "rounded-circle mr-4" %>
        <%= recommend.user.name %>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="recommend-edit-btn">
        <% if recommend.user == current_user %>
          <%= recommend.favorites.count %> <i class="fas fa-heart heart"></i>
          <span class="recommend-edit ml-3" data-toggle="modal" data-target="#editModal">
            <i class="fas fa-edit mr-2"></i>
          </span>
          <div id="editModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
            <%= render 'recommends/form', recommend: recommend %>
          </div>
        <% else %>
          <% unless current_user.is_admin == true %>
            <span class=<%= "favorite-" + recommend.id.to_s %> >
              <%= render 'favorites/btn', recommend: recommend %>
            </span>
          <% end %>
        <% end %>
        <% if recommend.user == current_user || current_user.is_admin == true %>
          <%= link_to recommend_path(recommend), method: :delete, data: {confirm: "本当に削除しますか？"} do %>
            <i class="fas fa-trash ml-1"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<% if current_page?(recommends_path) %>
  <div class="col-12 mt-5">
    <%= paginate recommends %>
  </div>
<% end %>

app/views/recommends/index.html.erb
<div class="mx-auto px-5">
  <%= render 'layouts/errors', obj: @recommend %>
  <div class="d-flex flex-wrap">
    <!--新規投稿-->
    <% if user_signed_in? %>
      <div class="m-3 pb-3 recommend-item">
        <div class="new-btn d-flex align-items-center justify-content-center" data-toggle="modal" data-target="#newModal">
          <div class="d-flex align-items-center justify-content-center">
            ♡
          </div>
        </div>
        <div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
          <%= render 'form', recommend: @recommend %>
        </div>
        <p class="text-center recommend-typing">new recommend</p>
      </div>
    <% end %>
    <!--一覧-->
    <%= render 'index', recommends: @recommends %>
  </div>
</div>