config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root :to => 'homes#top'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :favorites
      get :dm
    end
    get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw' => 'users#withdraw', as: 'withdraw'
  end

  resources :notifications, only: [:index]

  resources :want_items, only: [:index, :create, :update, :destroy] do
    resources :want_answers, only: [:create, :destroy]
    member do
      patch 'answer_close' => 'want_items#answer_close', as: 'answer_close'
    end
  end

  resources :recommends, only: [:index, :new, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :categories, only: [:show, :create, :destroy] do
    member do
      get 'want_item' => 'categories#want_item'
      get 'recommend' => 'categories#recommend'
    end
  end

  resources :category_groups, only: [:show, :create, :destroy] do
    member do
      get 'want_item' => 'category_groups#want_item'
      get 'recommend' => 'category_groups#recommend'
    end
  end

  resources :rooms, only: [:index]
  resources :letters, only: [:create]

  get '/search', to: 'searches#search'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :category_group
  has_many :want_items
  has_many :reommends
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def want_item
    @categories = Category.all
    @category = Category.find(params[:id])
    @want_items = @category.want_items.page(params[:page]).per(10).order(created_at: :desc)
  end

  def recommend
    @category = Category.find(params[:id])
    @recommends = Recommend.where(category_id: @category.id).page(params[:page]).per(8).order(created_at: :desc)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to want_items_path
    else
      redirect_to want_items_path
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to want_items_path
  end

  private
  def category_params
    params.require(:category).permit(:category_group_id, :name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= render 'layouts/errors', obj: category %>
<%= form_with model: category do |f| %>
  <div class="row mt-3">
    <div class="col-8 form-group">
      <%= f.collection_select(:category_group_id, CategoryGroup.all, :id, :name, {prompt: "　"}, {class: "form-control input-sm"}) %>
    </div>
    <div class="col-8 form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "shirts/pants/...etc" %>
    </div>
    <div class="col-8 form-group">
      <%= f.submit "add category", class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/categories/_index.html.erb
<!--カテゴリ一覧-->
<% CategoryGroup.all.each do |group| %>
<ul id="accordion_menu" class="mb-3 ml-3 list-unstyled">
  <li class="mb-2">
    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0" data-toggle="collapse" href="#group<%= group.id.to_s %>" aria-controls="#group<%= group.id.to_s %>" aria-expanded="false">
      <%= group.name %>
    </button>
    <% if user_signed_in? && current_user.is_admin == true %>
      <%= link_to category_group_path(group), method: :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
    <% end %>
  </li>
  <ul id="group<%= group.id.to_s %>" class="collapse btn-toggle-nav list-unstyled fw-normal pb-1 small" data-parent="#accordion_menu">
    <li>
      <%= link_to "All", want_item_category_group_path(group) %>
    </li>
    <% Category.where(category_group_id: group.id).each do |category| %>
      <li>
        <%= link_to category.name, want_item_category_path(category) %>
        <% if user_signed_in? && current_user.is_admin == true %>
          <%= link_to category_path(category), method: :delete do %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
</ul>
<% end %>
<% if user_signed_in? && current_user.is_admin == true %>
<!--大分類追加-->
  <%= render 'category_groups/form', group: group %>
<!--カテゴリ追加-->
  <%= render 'categories/form', category: category %>
<% end %>

app/views/categories/recommend.html.erb
<div class="mx-auto px-5">
  <div class="d-flex flex-wrap">
    <%= render 'recommends/index', recommends: @recommends %>
  </div>
</div>

app/views/categories/want_item.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4 side-menu">
      <div class="mb-2">
        <h5 class="mb-3 ja">カテゴリ</h5>
          <%= render 'categories/index', categories: @categories, category: Category.new, group: CategoryGroup.new %>
      </div>
      <div class="tag-menu">
        <h5 class="mb-3 ja">タグ</h5>
        <div>
          <% Tag.all.each do |tag| %>
            &ensp;
            <p class="want-tags">
              <%= link_to search_path(content: tag.name, model:"tag", method: "perfect") do %>
                <%= tag.name %>
              <% end %>
            </span>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8 main">
      <% if @want_items.present? %>
        <%= render 'want_items/index', want_items: @want_items %>
      <% else %>
        このカテゴリの投稿はありません
      <% end %>
    </div>
  </div>
</div>